Rectangle :: struct  {  // It is my personal style to capitalize the names of my structs, but it's not required.
    x0: float;   // X coordinate of lower-left corner.
    y0: float;   // Y coordinate of lower-left corner.
    x1: float;   // X coordinate of upper-right corner.
    y1: float;   // Y coordinate of upper-right corner.

    color_name: string;   // Maybe the name of a color we use to draw this, or ... something.
}
